# https://taskfile.dev

version: '3'

includes:
  config: ./config
  proto: tasks/proto.yml
  go: tasks/go.yml
  install: tasks/install.{{OS}}.yml
  build: tasks/build.{{OS}}.yml

tasks:
  default:
    cmds:
      - task: config:deploy
      - task: build:build
