# https://taskfile.dev

version: '3'

vars:
  PROTO_IN:           proto/mkit
  PROTO_OUT:          mkit
  GITHUB_REPO_OWNER:  xmlking
  GITHUB_REPO_NAME:   grpc-starter-kit
  GITHUB_REPO_URL:    https://github.com/{{.GITHUB_REPO_OWNER}}/{{.GITHUB_REPO_NAME}}.git
  GOPATH:
    sh: go env GOPATH
  GIT_COMMIT:
    sh: git log -n 1 --format=%h

env:
  FOO: foo

includes:
  config:     ./config
  proto:      task/proto.yml
  go:         task/go.yml
  install:    task/install.{{OS}}.yml
  build:      task/build.{{OS}}.yml

tasks:
  default:
    cmds:
      - task: config:deploy
      - task: build:build
