# https://taskfile.dev

version: '3'

vars:
  GOPATH:
    sh: go env GOPATH
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  GIT_REPO_URL:
    sh: git config --get remote.origin.url
  PROTO_IN:   proto/mkit
  PROTO_OUT:  mkit

env:
  FOO: foo


includes:
  config:     ./config
  proto:      task/proto.yml
  go:         task/go.yml
  install:    task/install.{{OS}}.yml
  build:      task/build.{{OS}}.yml

tasks:
  default:
    cmds:
      - task: config:deploy
      - task: build:build
