database:
  conn_max_lifetime: 2h
  database: "file:account?mode=memory&cache=shared&_fk=1"
email:
  from: from-test@gmail.com

services:
  account:
    endpoint: dns:///account.test:8080
    version: v0.1.0
    authority: aaa.bbb.ccc
