apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
#namespace: $(NS)
namespace: production
namePrefix: prod-
nameSuffix: -v1

commonLabels:
  environment: production
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am production!

resources:
  - ../../base/service
  - ../../base/envoy

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/health-sidecar.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  # - path: patches/resource_limit.yaml
  #   target:
  #     kind: Deployment
  #     labelSelector: app.kubernetes.io/component=microservice
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
#  - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - CONFY_ENV=production
      - CONFY_LOG_LEVEL=debug
      - CONFY_LOG_FORMAT=gcp
      - CONFY_FILE_PATH=/config/config.yml
      - CONFY_DEBUG_MODE=true
      - CONFY_VERBOSE_MODE=true
      - CONFY_USE_PKGER=true
      - CONFY_FEATURES_TLS_ENABLED=true
      - CONFY_FEATURES_RPCLOG_ENABLED=false
      - MICRO_BROKER=googlepubsub
      - GRPC_GO_LOG_SEVERITY_LEVEL="info"
      - GRPC_GO_LOG_VERBOSITY_LEVEL="99"
      # - INSECURE_SKIP_VERIFY=true
      # following endpoint overwrites (in config.yml)
      # - CONFY_SERVICES_ACCOUNT_ENDPOINT=$(ACCOUNT_SERVICE_ENDPOINT)
      # - CONFY_SERVICES_GREETER_ENDPOINT=$(GREETER_SERVICE_ENDPOINT)
      # - CONFY_SERVICES_EMAILER_SERVICE_ENDPOINT=$(EMAILER_SERVICE_ENDPOINT)
      # - CONFY_SERVICES_RECORDER_ENDPOINT=$(RECORDER_SERVICE_ENDPOINT)
secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=prod-real-pass
  # - name: registry-credentials
  #   files:
  #       - ".dockerconfigjson=docker.secret.json"
  #   type: kubernetes.io/dockerconfigjson

replicas:
  - name: service
    count: 1

images:
  - name: redis
    newTag: 5.0.9
  - name: quay.io/coreos/etcd
    newTag: v3.4.9
  - name: quay.io/coreos/etcd-operator
    newName: xmlking/etcd-operator
    newTag: v0.10.1
  - name: postgres
    newTag: 11.5-alpine
  - name: envoyproxy/envoy-alpine
    newName: docker.io/envoyproxy/envoy-alpine
    newTag: v1.14.2
  - name: micro/micro
    newName: ghcr.io/xmlking/grpc-starter-kit/micro
    newTag: v2.0.0
  - name: xmlking/account-service
    newName: ghcr.io/xmlking/grpc-starter-kit/account-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-service
    newName: ghcr.io/xmlking/grpc-starter-kit/emailer-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-service
    newName: ghcr.io/xmlking/grpc-starter-kit/greeter-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/recorder-service
    newName: ghcr.io/xmlking/grpc-starter-kit/recorder-service
    newTag: $(IMAGE_VERSION)
