apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account
  - emailer
  - greeter
  - recorder

configMapGenerator:
#  - name: env-vars
#    behavior: merge
  - name: env-vars-common
    literals:
      - CONFIGOR_ENV=development
      - CONFIGOR_LOG_LEVEL=debug
      - CONFIGOR_LOG_FORMAT=text
      - CONFIGOR_FILE_PATH=/config/config.yaml
      - CONFIGOR_DEBUG_MODE=true
      - CONFIGOR_VERBOSE_MODE=true
      - CONFIGOR_USE_PKGER=true
      - GRPC_GO_LOG_SEVERITY_LEVEL="info"
      - GRPC_GO_LOG_VERBOSITY_LEVEL="99"

#secretGenerator:
#   - name: app-tls
#     files:
#       - secret/tls.cert
#       - secret/tls.key
