apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account
  - emailer
  - greeter
  - recorder

configMapGenerator:
#  - name: env-vars
#    behavior: merge
  - name: env-vars-common
    literals:
      - CONFY_ENV=development
      - CONFY_LOG_LEVEL=debug
      - CONFY_LOG_FORMAT=text
      - CONFY_FILE_PATH=/config/config.yml
      - CONFY_DEBUG_MODE=true
      - CONFY_VERBOSE_MODE=true
      - CONFY_USE_PKGER=true
      - GRPC_GO_LOG_SEVERITY_LEVEL="info"
      - GRPC_GO_LOG_VERBOSITY_LEVEL="99"

#secretGenerator:
#   - name: app-tls
#     files:
#       - secret/tls.cert
#       - secret/tls.key
