apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  template:
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:latest
          imagePullPolicy: Always
          command:
            - envoy
          args:
            - '-c /etc/envoy/envoy.yaml'
            - '--service-node front'
            - '--service-cluster front'
            - '-l $(ENVOY_LOG_LEVEL)'
          envFrom:
            - configMapRef:
                name: env-vars
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
            - name: certs
              mountPath: /etc/certs
              readOnly: true
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              httpHeaders:
                - name: x-envoy-livenessprobe
                  value: healthz
              port: 9443
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              httpHeaders:
                - name: x-envoy-livenessprobe
                  value: healthz
              port: 9443
            initialDelaySeconds: 10
          ports:
            - name: admin
              containerPort: 9901
            - name: http # just for debugging, to be removed
              containerPort: 9090
            - name: https
              containerPort: 9443
      volumes:
        - name: config
          configMap:
            name: config
        - name: certs
          secret:
            secretName: certs
