name: Proto
on:
  push:
    paths:
      - '**.proto'
jobs:
  build:
    runs-on: ubuntu-latest
#    container: bufbuild/buf
    steps:
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - name: Install buf
        uses: wizhi/setup-buf@v1
        with:
          version: 0.35.1

#      - name: checkout-master
#        if: success()
#        uses: actions/checkout@v2
#        with:
#          ref: master
      - name: checkout
        if: success()
        uses: actions/checkout@v2

      - name: proto check
#        run: >-
#          git fetch --depth 1 origin master
#          task proto:breaking
        run: |
          git branch -f master origin/master
          task proto:breaking
