name: Proto
on:
  push:
    paths:
      - '**.proto'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: checkout-master
        run: git checkout master
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'

      - name: proto check
        run: >-
          task proto:breaking
